// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Application
{
	public class LoggerConfig
	{
		public static bool Enable=true;
		public static LoggerLevel Level=LoggerLevel.All;
	}

	public enum LoggerLevel
	{
		All,
		Debug,
		Warning,
		Error,
		Close
	}
}

